### ISSUE TITLE
Migration Exception

### ISSUE THREAD

**Issue by internetztube** [AcclaroInc/craft-translations#231]
Hi!

I am getting this migration exception when updating from `v1.10.6` to `v2.0.1`. 

```
- Craft version: 3.7.9 (Pro)
- PHP version: 7.3.28
- OS version: Linux 5.4.0-58-generic
- Database driver & version: PostgreSQL 10.6
- Plugins & versions: 
    - Translations v1.10.6
```

```
Database Exception: SQLSTATE[42710]: Duplicate object: 7 ERROR: constraint "translations_files_status_check" for relation "translations_files" already exists
The SQL being executed was: ALTER TABLE "translations_files" ALTER COLUMN "status" TYPE varchar(255), ALTER COLUMN "status" SET DEFAULT 'new', ALTER COLUMN "status" DROP NOT NULL, ADD CONSTRAINT translations_files_status_check CHECK ("status" in ('new','in progress','preview','ready for review','complete','canceled','published','failed'))

Migration: acclaro\translations\migrations\m210922_095949_add_ready_for_review_status

Output:

Altering translations_files status column...
> alter column status in table {{%translations_files}} to string DEFAULT 'new' CHECK ([[status]] in ('new','in progress','preview','ready for review','complete','canceled','published','failed')) ...Exception: SQLSTATE[42710]: Duplicate object: 7 ERROR: constraint "translations_files_status_check" for relation "translations_files" already exists
The SQL being executed was: ALTER TABLE "translations_files" ALTER COLUMN "status" TYPE varchar(255), ALTER COLUMN "status" SET DEFAULT 'new', ALTER COLUMN "status" DROP NOT NULL, ADD CONSTRAINT translations_files_status_check CHECK ("status" in ('new','in progress','preview','ready for review','complete','canceled','published','failed')) (/path/to/craft/src/vendor/yiisoft/yii2/db/Schema.php:678)
#0 /path/to/craft/src/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE "tr...')
#1 /path/to/craft/src/vendor/yiisoft/yii2/db/Command.php(1102): yii\db\Command->internalExecute('ALTER TABLE "tr...')
#2 /path/to/craft/src/vendor/yiisoft/yii2/db/Migration.php(420): yii\db\Command->execute()
#3 /path/to/craft/src/vendor/acclaro/translations/src/migrations/m210922_095949_add_ready_for_review_status.php(20): yii\db\Migration->alterColumn('{{%translations...', 'status', Object(yii\db\ColumnSchemaBuilder))
#4 /path/to/craft/src/vendor/craftcms/cms/src/db/Migration.php(52): acclaro\translations\migrations\m210922_095949_add_ready_for_review_status->safeUp()
#5 /path/to/craft/src/vendor/craftcms/cms/src/db/MigrationManager.php(232): craft\db\Migration->up(true)
#6 /path/to/craft/src/vendor/craftcms/cms/src/db/MigrationManager.php(148): craft\db\MigrationManager->migrateUp(Object(acclaro\translations\migrations\m210922_095949_add_ready_for_review_status))
#7 /path/to/craft/src/vendor/craftcms/cms/src/services/Updates.php(249): craft\db\MigrationManager->up()
#8 /path/to/craft/src/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(509): craft\services\Updates->runMigrations(Array)
#9 /path/to/craft/src/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#10 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#11 /path/to/craft/src/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /path/to/craft/src/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#13 /path/to/craft/src/vendor/craftcms/cms/src/web/Controller.php(189): yii\base\Controller->runAction('migrate', Array)
#14 /path/to/craft/src/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('migrate', Array)
#15 /path/to/craft/src/vendor/craftcms/cms/src/web/Application.php(277): yii\base\Module->runAction('updater/migrate', Array)
#16 /path/to/craft/src/vendor/craftcms/cms/src/web/Application.php(674): craft\web\Application->runAction('updater/migrate')
#17 /path/to/craft/src/vendor/craftcms/cms/src/web/Application.php(214): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /path/to/craft/src/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /path/to/craft/src/web/index.php(21): yii\base\Application->run()
#20 ~/.composer/vendor/laravel/valet/server.php(235): require('/~/...')
#21 {main}
```

**Comment by taylordaughtry** [comment]
@sidedwards  Hi! Is there a timeline for this, by chance? (We're also seeing the same issue with our client)
