### ISSUE TITLE
Couldn't install plugin

### ISSUE THREAD

**Issue by nicolasconnault** [AcclaroInc/craft-translations#5]
The plugin downloaded fine, and was added to composer just fine, but won't install in Craft.

Here's the log file:

```
$_POST = []

$_FILES = []

$_COOKIE = [
    '1031b8c41dfff97a311a7ac99863bdc5_username' => '19955e3010d8b407bca6a2303dc337e97735372e0cf5bda3f53cb69b25e1c4e8a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_username\";i:1;s:5:\"admin\";}'
    '__stripe_mid' => 'a3d2cff3-ef0b-4e1b-a027-8445e61df9be'
    '1031b8c41dfff97a311a7ac99863bdc5_identity' => '2a6147fe172f075b097109bb58f7f5ee5042074eaba9237377703c44f5d69095a:2:{i:0;s:41:\"1031b8c41dfff97a311a7ac99863bdc5_identity\";i:1;s:206:\"[1,\"[\\\"8oF_TQhR7TcoqyV_1Np6kQfpytrT-BtygP94JLujZexHsCSyM0mT-3BvUaHXpfqVoufouKpnG89-dP69isCDXMLr2ae6HYwCbtvY\\\",null,\\\"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0\\\"]\",1209600]\";}'
    'CraftSessionId' => 'j77rsjdlvsps0a7fn6k15qt31f'
    'CRAFT_CSRF_TOKEN' => '•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '__stripe_sid' => 'b4e6abcd-00ae-4ebe-a1ce-7475e80ddf0f'
]

$_SESSION = [
    'bd62416aa8538ede709019a5e113eea5__flash' => [
        'error' => 1
    ]
    '1031b8c41dfff97a311a7ac99863bdc5__token' => '••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••'
    '1031b8c41dfff97a311a7ac99863bdc5__id' => 1
    '1031b8c41dfff97a311a7ac99863bdc5__expire' => 1555469626
    'bd62416aa8538ede709019a5e113eea5__auth_access' => [
        0 => 'saveAssetInVolume:1'
    ]
    'error' => 'Couldn’t install plugin.'
]

$_SERVER = [
    'USER' => 'www-data'
    'HOME' => '/var/www'
    'HTTP_UPGRADE_INSECURE_REQUESTS' => '1'
    'HTTP_COOKIE' => '1031b8c41dfff97a311a7ac99863bdc5_username=19955e3010d8b407bca6a2303dc337e97735372e0cf5bda3f53cb69b25e1c4e8a%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_username%22%3Bi%3A1%3Bs%3A5%3A%22admin%22%3B%7D; __stripe_mid=a3d2cff3-ef0b-4e1b-a027-8445e61df9be; 1031b8c41dfff97a311a7ac99863bdc5_identity=2a6147fe172f075b097109bb58f7f5ee5042074eaba9237377703c44f5d69095a%3A2%3A%7Bi%3A0%3Bs%3A41%3A%221031b8c41dfff97a311a7ac99863bdc5_identity%22%3Bi%3A1%3Bs%3A206%3A%22%5B1%2C%22%5B%5C%228oF_TQhR7TcoqyV_1Np6kQfpytrT-BtygP94JLujZexHsCSyM0mT-3BvUaHXpfqVoufouKpnG89-dP69isCDXMLr2ae6HYwCbtvY%5C%22%2Cnull%2C%5C%22Mozilla%2F5.0+%28X11%3B+Ubuntu%3B+Linux+x86_64%3B+rv%3A66.0%29+Gecko%2F20100101+Firefox%2F66.0%5C%22%5D%22%2C1209600%5D%22%3B%7D; CraftSessionId=j77rsjdlvsps0a7fn6k15qt31f; CRAFT_CSRF_TOKEN=0413c990b163d7cf09e398265237edfd5f4666fe4022fd02bbc1a3bf3fe18815a%3A2%3A%7Bi%3A0%3Bs%3A16%3A%22CRAFT_CSRF_TOKEN%22%3Bi%3A1%3Bs%3A208%3A%22caTjblStr5-ZSxOiitoIqeUvl6Dfa54jx5jCQekM%7C2f91fce6d2090313bb2e235b00d24bd8a85fba7abfb64af139d3a1d4e76fc876caTjblStr5-ZSxOiitoIqeUvl6Dfa54jx5jCQekM%7C1%7C%242y%2413%24QmdByUScQyJw.Bix05UxvuCaZvRDmFVI0mZ0qSUAv5eCR44sA1bjq%22%3B%7D; __stripe_sid=b4e6abcd-00ae-4ebe-a1ce-7475e80ddf0f'
    'HTTP_CONNECTION' => 'keep-alive'
    'HTTP_REFERER' => 'http://lgp-global/admin/settings/plugins'
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate'
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.5'
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8'
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0'
    'HTTP_HOST' => 'lgp-global'
    'REDIRECT_STATUS' => '200'
    'SERVER_NAME' => 'lgp-global'
    'SERVER_PORT' => '80'
    'SERVER_ADDR' => '127.0.0.1'
    'REMOTE_PORT' => '46012'
    'REMOTE_ADDR' => '127.0.0.1'
    'SERVER_SOFTWARE' => 'nginx/1.14.0'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'REQUEST_SCHEME' => 'http'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'DOCUMENT_ROOT' => '/var/www/new-craft/web'
    'DOCUMENT_URI' => '/index.php'
    'REQUEST_URI' => '/admin/settings/plugins'
    'SCRIPT_NAME' => '/index.php'
    'CONTENT_LENGTH' => ''
    'CONTENT_TYPE' => ''
    'REQUEST_METHOD' => 'GET'
    'QUERY_STRING' => ''
    'SCRIPT_FILENAME' => '/var/www/new-craft/web/index.php'
    'FCGI_ROLE' => 'RESPONDER'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1555466026.3294
    'REQUEST_TIME' => 1555466026
    'ENVIRONMENT' => 'dev'
    'SECURITY_KEY' => '••••••••••••••••••••••••••••••••'
    'DB_DRIVER' => 'pgsql'
    'DB_SERVER' => 'localhost'
    'DB_USER' => 'nicolas'
    'DB_PASSWORD' => '•••••••'
    'DB_DATABASE' => 'lgp-global'
    'DB_SCHEMA' => 'public'
    'DB_TABLE_PREFIX' => ''
    'DB_PORT' => '5432'
    'DEFAULT_SITE_URL' => 'http://lgp-global'
]

```

And my composer.json file:
```
{
  "require": {
    "acclaro/translations": "1.0.2",
    "aelvan/mailchimp-subscribe": "v2.0.4",
    "angellco/spoon": "3.3.6",
    "barrelstrength/sprout-active": "2.0.9",
    "barrelstrength/sprout-forms": "3.0.0-beta.50",
    "barrelstrength/sprout-reports": "1.1.5",
    "craftcms/cms": "^3.0.0",
    "craftcms/contact-form": "2.2.4",
    "craftcms/element-api": "2.5.4",
    "craftcms/redactor": "2.3.2",
    "dolphiq/redirect": "1.0.20",
    "dolphiq/sitemap": "1.0.9",
    "dukt/videos": "2.0.6",
    "lukeyouell/craft-contactformtemplates": "1.0.1",
    "lukeyouell/craft-countryselect": "1.1.2",
    "lukeyouell/craft-mailchimplists": "1.0.5",
    "lukeyouell/craft-sentry": "1.5.1",
    "nerds-and-company/schematic": "4.1.1",
    "nystudio107/craft-fastcgicachebust": "1.0.8",
    "nystudio107/craft-seomatic": "3.1.47",
    "rias/craft-notifications": "1.1.1",
    "studioespresso/craft-dumper": "1.3.1",
    "superbig/craft3-http2serverpush": "1.0.1",
    "superbig/craft3-imgix": "2.0.4",
    "topshelfcraft/wordsmith": "3.0.4",
    "verbb/smith": "1.0.0",
    "verbb/super-table": "2.1.17",
    "vlucas/phpdotenv": "^2.4.0",
    "xpertbot/craft-wheelform": "1.25.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "7.2"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
    ]
  }
}
```

**Comment by sidedwards** [comment]
@nicolasconnault Are you receiving any errors after clicking "Install"?

**Comment by nicolasconnault** [comment]
@sidedwards yes, a red notification at the top saying "Couldn’t install plugin"
![Screenshot from 2019-04-17 10-12-19](https://user-images.githubusercontent.com/79558/56255951-5cb50080-60f9-11e9-997d-a003ede4b82a.png)

**Comment by nicolasconnault** [comment]
@sidedwards if I install via the Plugin Store, it goes through the updating of composer dependencies, then shows the Tick icon with "All done", but when I go to the list of installed plugins, it's listed as not installed.

**Comment by sidedwards** [comment]
@nicolasconnault Can you provide any additional PHP error logs?

**Comment by nicolasconnault** [comment]
Sorry there are no PHP errors being logged at all besides what's in storage/logs/web.log

**Comment by sidedwards** [comment]
@nicolasconnault Have you tried installing manually via the CLI?

```
composer require acclaro/translations

./craft install/plugin translations
```

Are there any errors that appear there?

**Comment by nicolasconnault** [comment]
@sidedwards aha! I think you have a postgresql incompatibility here:

```
*** installing translations
    > create table {{%translations_files}} ...Exception: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "values" does not exist
The SQL being executed was: CREATE TABLE "translations_files" (
	"id" serial NOT NULL PRIMARY KEY,
	"orderId" integer NOT NULL,
	"elementId" integer NOT NULL,
	"draftId" integer NOT NULL,
	"sourceSite" integer NOT NULL,
	"targetSite" integer NOT NULL,
	"status" varchar(255) DEFAULT 'new' CHECK ("values" in ('new','in progress','preview','complete','canceled','published')),
	"wordCount" integer,
	"source" text,
	"target" text,
	"previewUrl" varchar(255) DEFAULT '',
	"serviceFileId" varchar(255) DEFAULT '',
	"dateCreated" timestamp(0) NOT NULL,
	"dateUpdated" timestamp(0) NOT NULL,
	"uid" char(36) NOT NULL DEFAULT '0'
) (/var/old/new-craft/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /var/old/new-craft/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE "t...')
#1 /var/old/new-craft/vendor/yiisoft/yii2/db/Command.php(1091): yii\db\Command->internalExecute('CREATE TABLE "t...')
#2 /var/old/new-craft/vendor/yiisoft/yii2/db/Migration.php(323): yii\db\Command->execute()
#3 /var/old/new-craft/vendor/acclaro/translations/src/migrations/Install.php(89): yii\db\Migration->createTable('{{%translations...', Array)
#4 /var/old/new-craft/vendor/acclaro/translations/src/migrations/Install.php(40): acclaro\translations\migrations\Install->createTables()
#5 /var/old/new-craft/vendor/craftcms/cms/src/db/Migration.php(56): acclaro\translations\migrations\Install->safeUp()
#6 /var/old/new-craft/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /var/old/new-craft/vendor/craftcms/cms/src/base/Plugin.php(152): craft\db\MigrationManager->migrateUp(Object(acclaro\translations\migrations\Install))
#8 /var/old/new-craft/vendor/craftcms/cms/src/services/Plugins.php(520): craft\base\Plugin->install()
#9 /var/old/new-craft/vendor/craftcms/cms/src/console/controllers/InstallController.php(191): craft\services\Plugins->installPlugin('translations')
#10 [internal function]: craft\console\controllers\InstallController->actionPlugin('translations')
#11 /var/old/new-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /var/old/new-craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#13 /var/old/new-craft/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('plugin', Array)
#14 /var/old/new-craft/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('plugin', Array)
#15 /var/old/new-craft/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('install/plugin', Array)
#16 /var/old/new-craft/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('install/plugin', Array)
#17 /var/old/new-craft/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('install/plugin', Array)
#18 /var/old/new-craft/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#19 /var/old/new-craft/craft(22): yii\base\Application->run()
#20 {main}
*** installed translations successfully (time: 0.285s)
```

**Comment by nicolasconnault** [comment]
Fixed the installation by replacing 'values' with 'status' on lines 81, 123, 150 of src/migrations/install.php

**Comment by sidedwards** [comment]
Hi @nicolasconnault, thanks for submitting these issues. We're working on adding better support for PostgreSQL. I'll include fixes for https://github.com/AcclaroInc/craft-translations/issues/5, https://github.com/AcclaroInc/craft-translations/issues/7, in a 1.1.0 version of the plugin. Thanks for your patience while we resolve these.

**Comment by nicolasconnault** [comment]
Thanks!

Just curious, how many sales have you had? Because $1,000 for a module is a
LOT of money, plus you have to pay extra for translation services.
Also, Craft CMS already has multi-language support, so I'm not sure what
your extension brings to the platform.

Regards,

Nicolas Connault
-------------------------------
Skype: nicolasconnault
Blog: http://nicolasconnault.wordpress.com
Photos: http://www.flickr.com/nicolasconnault
Twitter: nicolasconnault

**Comment by sidedwards** [comment]
@nicolasconnault Thanks for the input! It's currently geared towards enterprise-level multi-sites with large quantities of entries that need translations. Craft does support multi-language in the sense that it allows you to store field values per site but with hundreds or thousands of entries, it can become difficult to manage.

The plugin allows entry content to be bulk translated from a source language (English for example) to other target languages without having to copy/paste while also preserving the entry field structure. This can save a TON of time when dealing with large entry counts.

**Comment by vikdialpad** [comment]
@sidedwards 
Hi there, I'm also trying to install on a Postgres DB and am getting the following error:
`db_1        | 2019-06-11 23:36:47.850 UTC [207] ERROR:  column "values" does not exist
db_1        | 2019-06-11 23:36:47.850 UTC [207] STATEMENT:  CREATE TABLE "dp_translations_files" (
db_1        | 		"id" serial NOT NULL PRIMARY KEY,
db_1        | 		"orderId" integer NOT NULL,
db_1        | 		"elementId" integer NOT NULL,
db_1        | 		"draftId" integer NOT NULL,
db_1        | 		"sourceSite" integer NOT NULL,
db_1        | 		"targetSite" integer NOT NULL,
db_1        | 		"status" varchar(255) DEFAULT 'new' CHECK ("values" in ('new','in progress','preview','complete','canceled','published')),
db_1        | 		"wordCount" integer,
db_1        | 		"source" text,
db_1        | 		"target" text,
db_1        | 		"previewUrl" varchar(255) DEFAULT '',
db_1        | 		"serviceFileId" varchar(255) DEFAULT '',
db_1        | 		"dateCreated" timestamp(0) NOT NULL,
db_1        | 		"dateUpdated" timestamp(0) NOT NULL,
db_1        | 		"uid" char(36) NOT NULL DEFAULT '0'
`
When will version 1.1.0 / postgres support be available ?

**Comment by sidedwards** [comment]
Hi @vikdialpad, thanks for reaching out. PostgreSQL support is at the top of our list for our next release which will be available early next week. I'll post an update in this thread as soon as it's released.

**Comment by vikdialpad** [comment]
Thanks for the follow up, that's great to hear. We're looking forward to the added postgres support.

**Comment by sidedwards** [comment]
Hi, @vikdialpad @nicolasconnault Thanks for you're patience while we worked on this issue. I just wanted to inform you that [v1.1.0](https://github.com/AcclaroInc/craft-translations/releases/tag/1.1.0) includes support for PostgreSQL databases.
