### ISSUE TITLE
Migration: column "activitylog" does not exist

### ISSUE THREAD

**Issue by internetztube** [AcclaroInc/craft-translations#508]
Hey!

We wanted to update the plugin from `v3.3.3` → `v3.3.6`. During the migration the following error is occurring: 

```
Performing update with Composer ... done
Applying new migrations ... error: The command "'/opt/homebrew/Cellar/php/8.3.4/bin/php' '/path/to/app/src/craft' 'migrate/all' '--no-backup' '--no-content'" failed.

Exit Code: 1(General error)

Working directory: /path/to/app/src

Output:
================
Checking for pending Craft and plugin migrations ...
Total 1 new Translations migration to be applied:
    - m240117_112821_create_activity_logs_table

*** applying m240117_112821_create_activity_logs_table
    > create table {{%translations_activitylogs}} ... done (time: 0.110s)
    > create index idx_alwooracvwfcqudvamjgnbqmznrjoeruczzh on {{%translations_activitylogs}} (targetId) ... done (time: 0.005s)
    > create index idx_gkumlvgghdzbcjqitisezrmodpryfvrttaxw on {{%translations_activitylogs}} (targetClass) ... done (time: 0.003s)
Exception: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "activitylog" does not exist
LINE 1: SELECT id, activityLog FROM "translations_orders"
                   ^
HINT:  Perhaps you meant to reference the column "translations_orders.activityLog".
The SQL being executed was: SELECT id, activityLog FROM "translations_orders" (/path/to/app/src/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /path/to/app/src/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'SELECT id, acti...')
#1 /path/to/app/src/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute('SELECT id, acti...')
#2 /path/to/app/src/vendor/yiisoft/yii2/db/Command.php(417): yii\db\Command->queryInternal('fetchAll', NULL)
#3 /path/to/app/src/vendor/acclaro/translations/src/migrations/m240117_112821_create_activity_logs_table.php(32): yii\db\Command->queryAll()
#4 /path/to/app/src/vendor/craftcms/cms/src/db/Migration.php(50): acclaro\translations\migrations\m240117_112821_create_activity_logs_table->safeUp()
#5 /path/to/app/src/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#6 /path/to/app/src/vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp('m240117_112821_...')
#7 [internal function]: craft\console\controllers\MigrateController->actionAll()
#8 /path/to/app/src/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /path/to/app/src/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#10 /path/to/app/src/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#11 /path/to/app/src/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('all', Array)
#12 /path/to/app/src/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#13 /path/to/app/src/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#14 /path/to/app/src/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#15 /path/to/app/src/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#16 /path/to/app/src/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#17 /path/to/app/src/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#18 /path/to/app/src/craft(22): yii\base\Application->run()
#19 {main}
*** failed to apply m240117_112821_create_activity_logs_table (time: 0.172s)
```

<table class="data fullwidth fixed-layout" dir="ltr">
        <tbody>
                            <tr>
                    <th class="light">PHP version</th>
                    <td>8.1.28</td>
                </tr>
                            <tr>
                    <th class="light">Database driver &amp; version</th>
                    <td>PostgreSQL 14.10</td>
                </tr>
                            <tr>
                    <th class="light">Craft edition &amp; version</th>
                    <td>Craft Pro 4.10.0</td>
                </tr>                    </tbody>
    </table>

**Comment by internetztube** [comment]
Any Updates?

**Comment by MerrittBoydston** [comment]
Hi @internetztube, we have released a fix for this issue. Please upgrade to `v3.4.0`.

**Comment by internetztube** [comment]
Thank you!

**Comment by MerrittBoydston** [comment]
> Thank you!

Please let me know if this upgrade resolved your issue. If so, I will close this ticket.
