### ISSUE TITLE
cURL error 28: Operation timed out after 2000 milliseconds with 0 out of 0 bytes received

### ISSUE THREAD

**Issue by nicolasconnault** [AcclaroInc/craft-translations#6]
After successful installation, accessing the Translations menu gives this error:
(I do have to wonder why this module costs $1,000 when it's so buggy)
```
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 2000 milliseconds with 0 out of 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185
Stack trace:
#0 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Middleware.php(60): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('get', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /var/old/new-craft/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\Client->request('get', 'feed/', Array)
#14 /var/old/new-craft/vendor/acclaro/translations/src/widgets/News.php(122): GuzzleHttp\Client->__call('get', Array)
#15 /var/old/new-craft/vendor/acclaro/translations/src/widgets/News.php(85): acclaro\translations\widgets\News->_getArticles()
#16 /var/old/new-craft/vendor/acclaro/translations/src/controllers/WidgetController.php(804): acclaro\translations\widgets\News->getBodyHtml()
#17 /var/old/new-craft/vendor/acclaro/translations/src/controllers/WidgetController.php(135): acclaro\translations\controllers\WidgetController->_getWidgetInfo(Object(acclaro\translations\widgets\News))
#18 [internal function]: acclaro\translations\controllers\WidgetController->actionIndex()
#19 /var/old/new-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#20 /var/old/new-craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#21 /var/old/new-craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('index', Array)
#22 /var/old/new-craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('index', Array)
#23 /var/old/new-craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('translations/wi...', Array)
#24 /var/old/new-craft/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('translations/wi...', Array)
#25 /var/old/new-craft/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#26 /var/old/new-craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#27 /var/old/new-craft/web/index.php(21): yii\base\Application->run()
#28 {main}
```

**Comment by sidedwards** [comment]
This is due to a low PHP timeout setting when trying to fetch data for the News dashboard widget.

Ensure that you're using a [recent version of cURL on the server](https://docs.craftcms.com/v3/requirements.html#required-php-extensions)

Try bumping your [PHP max_execution_time to the default setting](https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time)

If neither of those work, you can disable the News widget via the dashboard or the database in the `translations_widgets` table.
