### ISSUE TITLE
Can't create a new translator entry

### ISSUE THREAD

**Issue by nicolasconnault** [AcclaroInc/craft-translations#7]
Tried to create an import/export translator, and this error came up:
```
PDOException: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, , export_import, ["2"], active, [], 2019-04-17 06:33:55, 2019-04-17 06:33:55, 47105d0a-8cdd-4f23-b79a-93058119f885). in /var/old/new-craft/vendor/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 /var/old/new-craft/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /var/old/new-craft/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('INSERT INTO "tr...')
#2 /var/old/new-craft/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/old/new-craft/vendor/yiisoft/yii2/db/pgsql/Schema.php(617): yii\db\Command->queryOne()
#4 /var/old/new-craft/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\pgsql\Schema->insert('{{%translations...', Array)
#5 /var/old/new-craft/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#6 /var/old/new-craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#7 /var/old/new-craft/vendor/acclaro/translations/src/services/repository/TranslatorRepository.php(166): yii\db\BaseActiveRecord->save(false)
#8 /var/old/new-craft/vendor/acclaro/translations/src/controllers/BaseController.php(909): acclaro\translations\services\repository\TranslatorRepository->saveTranslator(Object(acclaro\translations\models\TranslatorModel))
#9 [internal function]: acclaro\translations\controllers\BaseController->actionSaveTranslator()
#10 /var/old/new-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/old/new-craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /var/old/new-craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-translator', Array)
#13 /var/old/new-craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-translator', Array)
#14 /var/old/new-craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('translations/ba...', Array)
#15 /var/old/new-craft/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('translations/ba...', Array)
#16 /var/old/new-craft/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /var/old/new-craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/old/new-craft/web/index.php(21): yii\base\Application->run()
#19 {main}

Next yii\db\IntegrityException: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, , export_import, ["2"], active, [], 2019-04-17 06:33:55, 2019-04-17 06:33:55, 47105d0a-8cdd-4f23-b79a-93058119f885).
The SQL being executed was: INSERT INTO "translations_translators" ("id", "status", "service", "label", "sites", "settings", "dateCreated", "uid", "dateUpdated") VALUES (NULL, 'active', 'export_import', '', '["2"]', '[]', '2019-04-17 06:33:55', '47105d0a-8cdd-4f23-b79a-93058119f885', '2019-04-17 06:33:55') RETURNING "id" in /var/old/new-craft/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /var/old/new-craft/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO "tr...')
#1 /var/old/new-craft/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('INSERT INTO "tr...')
#2 /var/old/new-craft/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/old/new-craft/vendor/yiisoft/yii2/db/pgsql/Schema.php(617): yii\db\Command->queryOne()
#4 /var/old/new-craft/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\pgsql\Schema->insert('{{%translations...', Array)
#5 /var/old/new-craft/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#6 /var/old/new-craft/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(false, NULL)
#7 /var/old/new-craft/vendor/acclaro/translations/src/services/repository/TranslatorRepository.php(166): yii\db\BaseActiveRecord->save(false)
#8 /var/old/new-craft/vendor/acclaro/translations/src/controllers/BaseController.php(909): acclaro\translations\services\repository\TranslatorRepository->saveTranslator(Object(acclaro\translations\models\TranslatorModel))
#9 [internal function]: acclaro\translations\controllers\BaseController->actionSaveTranslator()
#10 /var/old/new-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#11 /var/old/new-craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#12 /var/old/new-craft/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('save-translator', Array)
#13 /var/old/new-craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-translator', Array)
#14 /var/old/new-craft/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('translations/ba...', Array)
#15 /var/old/new-craft/vendor/craftcms/cms/src/web/Application.php(561): craft\web\Application->runAction('translations/ba...', Array)
#16 /var/old/new-craft/vendor/craftcms/cms/src/web/Application.php(281): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /var/old/new-craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /var/old/new-craft/web/index.php(21): yii\base\Application->run()
#19 {main}
Additional Information:
Array
(
    [0] => 23502
    [1] => 7
    [2] => ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, , export_import, ["2"], active, [], 2019-04-17 06:33:55, 2019-04-17 06:33:55, 47105d0a-8cdd-4f23-b79a-93058119f885).
)
```

**Comment by sidedwards** [comment]
Fixed in [v.1.1.0](https://github.com/AcclaroInc/craft-translations/releases/tag/1.1.0)
